<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions 
	 xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	 xmlns:tns="urn://co-opbank.co.ke/CommonServices/TS/Util/CreateExceptionEvent" 
	 xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
	 xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	 name="CreateExceptionEvent" targetNamespace="urn://co-opbank.co.ke/CommonServices/TS/Util/CreateExceptionEvent" 
	 xmlns:extns="urn://co-opbank.co.ke/CommonServices/Message/TS/Util/Sub/CreateExceptionEvent">
	 
  <wsdl:types>
    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    	<xsd:import 
    		schemaLocation="../../../../../Schemas/CommonServices/Message/TS/Util/Sub/CreateExceptionEvent.xsd" 
    		namespace="urn://co-opbank.co.ke/CommonServices/Message/TS/Util/Sub/CreateExceptionEvent">
    	</xsd:import>
    </xsd:schema>
  </wsdl:types>

  <wsdl:message name="CreateExceptionEventRequest">
  	<wsdl:part name="parameters"
  		element="extns:CreateExceptionEventRequest">
  	</wsdl:part>
  </wsdl:message>
  <wsdl:message name="CreateExceptionEventResponse">
  	<wsdl:part name="parameters"
  		element="extns:CreateExceptionEventResponse">
  	</wsdl:part>
  </wsdl:message>
  
  <wsdl:portType name="CreateExceptionEvent">
    <wsdl:operation name="CreateExceptionEvent">
    	<wsdl:input message="tns:CreateExceptionEventRequest"></wsdl:input>
    	<wsdl:output message="tns:CreateExceptionEventResponse"></wsdl:output>
    </wsdl:operation>
  </wsdl:portType>

</wsdl:definitions>
